spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-dll: true
    open-session-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    path: /h2-console
    console.enabled: true
#  mvc:  #these lines may or may not be necessary; swagger seems to be non-deterministic about what it needs to get /api to work
#    pathmatch:
#      matching-strategy: ant-path-matcher

server:
  port: 8081

hibernate:
  dialect: "org.hibernate.dialect.H2Dialect"


