spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-dll: true
    open-session-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    path: /h2-console
    console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
#  sql:
#    init:
#      data-locations: classpath:data.sql

hibernate:
  dialect: "org.hibernate.dialect.H2Dialect"


